apiVersion: v1
kind: Service
metadata:
  name: chronix
  namespace: logisland
spec:
  ports:
    - name: solr
      port: 8983
      protocol: TCP
      targetPort: chronix
  selector:
    app: chronix
  sessionAffinity: None
  type: ClusterIP
