apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logisland
  labels:
    component: kibana
spec:
  type: ClusterIP
  selector:
    run: kibana
  ports:
    - name: http
      port: 5601
      protocol: TCP